workflows:
  android-debug:
    name: Android debug APK
    instance_type: linux_x2
    scripts:
      - name: Build debug APK
        script: gradle --no-daemon assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
